### ISSUE TITLE
Add block option to emeraid-dialer app.

### ISSUE THREAD

**Issue by pzdawood** [HenriDellal/emerald-dialer#54] opened 2019-07-12 06:49 UTC
***proposal***
My suggestion is to add block option to the emeraid-dialer app. The block botton is used to stop  calls from the numbers that of which we are not Interested to take calls.
***Examples***
After adding the block option to this app the app looks like this
![PicsArt_07-12-12 05 22](https://user-images.githubusercontent.com/38599784/61108061-fe50b180-a49e-11e9-8d31-7103988cceef.png)
***Benefits of addy this option***
The benefit of this option is that when any person disturbs us by calling we can block it and after blocking it he can't able to call us.

**Comment by HenriDellal** [comment] 2019-07-14 11:18
Duplicate of #41

**Closed by HenriDellal** 2019-07-14 11:18 UTC
