### ISSUE TITLE
call

### ISSUE THREAD

**Issue by userkilled** [HenriDellal/emerald-dialer#51] opened 2019-06-03 18:26 UTC
When will I be able to call using your application, and not third-party?

**Comment by HenriDellal** [comment] 2019-06-03 19:06
I can't tell if it's going to happen soon. I really want to add this feature for a long time, but even moving code from AOSP dialer and adjusting it to the codebase requires a lot of time.
This issue is duplicate of #19, so I have to close it.

**Closed by HenriDellal** 2019-06-03 19:06 UTC
